### ISSUE TITLE
Órarend és osztályátlag elmentése

### ISSUE THREAD

**Issue by Pearoo-XD** [filc/naplo-2-legacy#173]
Sokszor csak meg szeretném nézni az órarendet a buszon, de nem érem el, mert nincsen elmentve. Jó lenne, ha lementené a legutóbb látott órarendet az app, és azt töltené be az app.
Ugyan ezt meg lehetne csinálni az osztályátlaggal.

**Comment by 55nknown** [comment]
Hanyas verzión vagy?

**Comment by RedyAu** [comment]
Frissíts a legfrissebb verzióra, és a jelenlegi repóra nyiss issuet ha még mindig fennáll a probléma.

https://filcnaplo.hu/downloads
https://github.com/filc/naplo
