### ISSUE TITLE
"Mi lenne ha nem..."

### ISSUE THREAD

**Issue by PandaDriver156** [filc/naplo-2-legacy#96]
Hasznos lenne, ha a Szellemjegyekhez hasonlóan megnézhetnénk,  hogy milyen lehetne az átlagunk ha egy bizonyos jegyet *nem* kaptunk volna meg

**Comment by StokiBoti** [comment]
Ne bolygassuk a múltunkat, a jövőre koncentráljunk :D

**Comment by RedyAu** [comment]
Ez már korábban is felmerült, esetleg tudsz mondani egy példát, hogy mikor lenne hasznos? Csak mert a UI-ba nehezen férne bele szépen.

**Comment by RedyAu** [comment]
Szavazunk róla a szerveren, ha több mint 50% igény van rá, és szépen megoldható, megoldjuk.

**Comment by RedyAu** [comment]
![image](https://user-images.githubusercontent.com/12989935/104781249-6bbf5b80-5782-11eb-98a1-19fe5c7a5b6b.png)
Úgy tűnik, lesz :D
Nem ígérjük, hogy hamar, de lesz.
